### ISSUE TITLE
Get the plugins working under cmake

### ISSUE THREAD

**Issue by millapet** [cepek/qgama21#2]
Original message:
----------------------------------------------------------------
V projektu gama-qt jsem měl
od počátku pluginy. Je tam použitý jakýsi fígl (hack), který mi poradil
kdysi Leoš Mervart a který se mi nelíbil už tehdy, ale fungovalo to.
Další problém je, že projekt byl kdysi v qmake  a já naletě zprávám, že
ve verzi Qt6 bude standardem cmake a v cmake se mi neporařilo ty pluginy
rozběhnout, takže jsem je dočasně opustil. Mohla by ses na to tedy
prosím podívat?  Doporučuji začít tím, že si pluginy vuzkoušíš mimo gamu
(jako cmake projekty) a teprve pak to zkusíš použít v gamě (tj. naučit
se správu pluginů s výhledem na Qt6).

**Comment by cepek** [comment]
Opisuji ze svého email:

Ahoj, já ty pluginy "odložil" a v podstatě i vytěsnil z paměti.
Sestavení demo pluginů jsem měl v qmake projektu, soubor gama-qt.pro je
na gitu ve  verzi gama-q2-1-02. Je to tam zakomentářované, což půjde v
CMakeLists.txt udělat elegantněji přes nějakou proměnnou. Měly by se
automaticky zobrazit pokud binárky nakopíruješ do adresáře ve kterém je
binárka gama-q2. Já bych se docela přimlouval nechat to až do příští
verze, protože jinak tu stávají nikdy neuzavřeme. Pluginy nejsou, kak
říká Sheldon Cooper žádné raketové inženýrství (nebo je to Howard
Wolowitz?) žádné raketové inženýrství, já je odložil s přechodem na
cmake, který už snad máme víceméně hotový.

Ten odkaz v QuickStart.txt bych asi odstranil. Qsqlite databázi vytváří
gama-q2 a SQL schéma je v qrc adresáři, co se nové verze týče, napíšu
posznámku do Issues.

**Comment by millapet** [comment]
O sestavení pluginů pod qgamou ani tak nejde, to už mám u sebe hotové. Spíš by mě zajímalo, co ty pluginy ze složky gama-q2-plugins dělají? 
Klidně to můžeme nechat až do další verze, to není problém.

**Comment by cepek** [comment]
Jeden byl opravdu jen banální demo,vypsal tuším nějakou tabulku, druhý
podle názvu měl udělat vyrovnání, ale už si to nepamatuju. Něco doplnim k
issue ohledně výšek stroje a cíle, resp. redukcím
Aleš

**Comment by cepek** [comment]
Ve verzi Qt6 vše chodí jak má.
